
# This config file is used to generate the runtime config file and the
# docker run command line.  If the app will not be run inside a container,
# this config file can be used as the runtime config.

# directories to be watched
# name: this can be anything, but it must be unique
# path: the path to the directory, from the perspective of the app on the host
#       to generate a config file with the paths updated to the perspective
#       of the container, use the --generate-docker-command option
# webhook_url: the URL to hit when the directory changes.  In this example, I'm using
#              webhooks created by the Scrypted webhook plugin
# watched_actions: the actions to watch for (e.g., CREATE, MODIFY, DELETE). If this
#                  section is missing, the default is 'CREATE'

directories:
  - name: Cam90
    path: /Users/jgbaum/projects/dirhooker/testc/cam90
    webhook_url: http://192.168.1.129:11080/endpoint/@scrypted/webhook/public/76/7agce62f2g7555b3/turnOn
    watched_actions: 
     - CREATE
  - name: Cam91
    path: /Users/jgbaum/projects/dirhooker/testc/cam91
    webhook_url: http://192.168.1.129:11080/endpoint/@scrypted/webhook/public/65/7c9dgfe3bnd65e56/turnOn
    watched_actions:
      - CREATE
  - name: Cam92
    path: /Users/jgbaum/projects/dirhooker/testc/cam92
    webhook_url: http://192.168.15.129:11080/endpoint/@scrypted/webhook/public/55/68b9hb7afbfd6243/turnOn
    watched_actions:
      - CREATE
  - name: Cam93
    path: /Users/jgbaum/projects/dirhooker/testc/cam93
    webhook_url: http://192.168.15.129:11080/endpoint/@scrypted/webhook/public/53/70a48h53425n5231/turnOn
    watched_actions:
      - CREATE
      - MODIFY